### PR TITLE
Proposal of POD Management

### LINKED ISSUE #4: POD directory standard
As our application must access some routes that could be uploaded by different applications, we think it would be easier if all of us use the same directory to save the routes in the POD. For example, when a user uploads a route, store it in a direcory called "ViadeRoutes".

viade_es4c team

### LINKED ISSUE #22: Using JSON-LD to represent the routes
This issue was requested by @labra to talk about the file format decision exposed in #21 

We have identify this as a tradeoff, therefore we can point out advantages and disadvantages. 

One the one hand, it is just a json with a "@context" property, we have already learned how to handle this format in the degree. Futhermore, javascript has a built-in object called JSON, that can help us with the parsing of the file. 

On the other hand, JSON-LDis not yet supported by the pod, what does this mean? The POD cannot show its contents as a turtle file, that is we cannot navigate the data graph. 

Summing up, we can use a format we are familiar with, really well documented, and based in something that it is really common, as it is JSON. As temporal consequence of that, we don't have support for it in the pod (but it can store it without any problem). Why I say temporal? The POD specification stated that it must support JSON-LD so if we use it  correctly, eventually the POD will be able to manage it.

JSON-LD specification: https://www.w3.org/TR/json-ld/

### LINKED ISSUE #23: The folder structure in the POD
This issue was requested by @labra to talk about the directory structure exposed in #21

As a summary of the related information in the pull request. We propose a viade/ folder in the root of the POD, here we should store the data related with the app. Inside it we will have other three folders: routes/, comments/, resources/. I believe that they are self-explanatory.

Why should we do it that way?

We could each of us (teams) have our own way to handle this, but supposing that one user used several of our apps, that would lead to a complex or even crazy structure of the user's POD data.

This is just a proposal that we consider pretty intuitive both for us and the user.

### LINKED ISSUE #24: How to handle the GPX information when routes are represented as JSON-LD
The issue was requested by @labra to talk about the way of managing the gpx data in #21 

This topic was not really specified in the pull request, since we have focused in the POD storage. However we have studied the gpx standard and we have come to the following conclusions. Everything that it is commented here can be seen in the web of the schema of GPX 1.1
https://www.topografix.com/GPX/1/1/gpx.xsd

I'm providing here a simple example of a gpx: https://pastebin.com/Siq5xNv2

In this example we only have one trk, but we could have more than one according to the GPX specification. According to the schema, a trk is: "trk represents a track - an ordered list of points describing a path." This stands as what we should understand as a route. As it is commented in #21 we believe that we must join keeping the order of all the trkpt inside the trk and assign it to the variable viade:points of the JSON-LD. Note that trk can have name, description, etc. so we can directly check for that properties.

There are two types of nodes, "wpt" and "trkpt", as far as we could understand a Waypoint  (wpt) stands a remarkable point in the route, for instance "Catedral de Oviedo", whereas a Trackpoint (trkpt) would stand as a point the user passed through. 

Having said so, it could be interesting to add to #21 JSON-LD the waypoints, what do you think about that? Also, provided a gpx with several "trk", we believe that we should import each of them as different routes, do you agree?

### LINKED ISSUE #28: Add "waypoints" to the specification
Adding "waypoints" optionally as a list of points with latitude, longitude, name and description.

### LINKED ISSUE #29: Add "author" to the specification
Adding "author" optionally with the webId of the route creator in the route file.

### LINKED ISSUE #30: Usage of json to store comments in jsonld specification
Using json to store comments instead of txt, with content and date.

### LINKED ISSUE #33: Issue with posting comments in routes.
It has been said that the comments will be stored in the pod of the user who comments and the route file will have the URI of that comment, but the user commenting should only have read permissions on the route file so it's not possible to add that URI. I think the best solution is to have another file, where the other users have permission to add and read information, but not to change it, so comment URIs can be added there, this way the route file cannot be modified by other users and they can still post comments by adding the URI to the comment file associated with that route. The comments property in the route file should be changed from a list of URIs to a single URI pointing that comment file that contains the list of comments URIs. I propose to include inside viade/comments 2 new folders, myComments to store the files that were stored before (the comments done by the pod's user), in the viade/comments, and myRoutesComments, to store the files containing the comments URIs done to the routes of pod's user. So this way a route has 2 files, one for all the route data itself with only read permissions in viade/routes, and another one which has the comments data with post permissions (read and add new information) in viade/comments/myRoutesComments.

### LINKED ISSUE #35: Add "date" to the specification
I think we should also add a "date" as optional in the route specification. Right now, in the last update, the specification recognizes date in comments, but taking this field into the route itself could be useful to represent the date in which it was done.

The date should be included in the context with something like:
```
"date": {
      "@id": "schema:Date",
      "@type": "xsd:date"
},
```

### PR DESCRIPTION
**Pull request by luispc1998**
This is a proposal of a possible management of the POD of the Viade apps. From the group en2a we expect that this proposal can be taken into account by other groups in order to achieve the interoperability beetwen our apps.

### CODE REVIEW

**Comment by luispc1998** [comment]
I didn't add it to the index file, if I should do so, please tell me before merging it.

**Review by labra — COMMENTED** [review]
I think it would be easier to track this pull request if you create one or more issues first to discuss it. 

Reading your proposal, I can see several issues that could be separately discussed: 
- Using JSON-LD to represent the routes
- The folder structure
- How to handle the GPX information when routes are represented as JSON-LD

**Comment by UO265180** [comment]
My group (es2a) has a few suggestions:
- Storing routes using a UUID as filename (i.e: ...routes/e90d146c-d7ab-42f9-a2de-5c32aeab8839.jsonld) to easily fetch the route using only that Id and avoiding storing the whole URL.
- When storing route points, changing "latitude" and "longitude" keys to "lat" and "lng" respectively. That's because Google Maps React Library, uses that naming, which simplifies route representation.
- In addition to the above, we suggest storing optionally name and point description.
- Another thing to comment, we think that it would be better to store comments with .jsonld format instead of .txt, that's because we don't want to store its content only, but adding some attributes like date (in millis/secs), author, optionally the point index which comment refers to (to be able to comment refering to a specific point) ... i.e: `{ content: "Muy wapa la ruta", date: 1584972023423, author: "https://marcosav.inrupt.net/profile/card#me", point: 1, route: "e90d146c-d7ab-42f9-a2de-5c32aeab8839" }`

**Comment by labra** [comment]
> My group (es2a) has a few suggestions:
> 
> * Storing routes using a UUID as filename (i.e: ...routes/e90d146c-d7ab-42f9-a2de-5c32aeab8839.jsonld) to easily fetch the route using only that Id and avoiding storing the whole URL.
> * When storing route points, changing "latitude" and "longitude" keys to "lat" and "lng" respectively. That's because Google Maps React Library, uses that naming, which simplifies route representation.
> * In addition to the above, we suggest storing optionally name and point description.
> * Another thing to comment, we think that it would be better to store comments with .jsonld format instead of .txt, that's because we don't want to store its content only, but adding some attributes like date (in millis/secs), author, optionally the point index which comment refers to (to be able to comment refering to a specific point) ... i.e: `{ content: "Muy wapa la ruta", date: 1584972023423, author: "https://marcosav.inrupt.net/profile/card#me", point: 1, route: "e90d146c-d7ab-42f9-a2de-5c32aeab8839" }`

Thanks for your comments. As I said before, I think it will be easier to discuss all those points separately with different issues and maybe once they are solved, we could improve this pull request taking into account the agreed resolutions...or using different pull requests for each of them.

**Comment by luispc1998** [comment]
I have just updated the proposal, according to issues: #28, #29, #30 and #33 
This stands as a summary:
- Added elevation for the points.
- Added waypoints.
- Added author
- Comment system changed. Now the route points to a file that points to the comment.

**Comment by uo265363** [comment]
Rdf namespace (http://www.w3.org/2000/01/rdf-schema#) is included in the context but is never used in route files. Same for xml shema (http://www.w3.org/2001/XMLSchema#) and viade:comment in comments jsonld. Is there a reason for that? Or is just an error?

**Comment by luispc1998** [comment]
It is not necessary since as you say is not used in the context, I included it because of two reasons. The first one is that the proposal of @labra used that namespaces, I wanted to show that we can use them too. The second one is that in case that someone wanted to propose a new property, they can easily check in one of those namespaces if such a property already exists. In the end, I checked myself the documents to see if some properties matched. In fact I put exactly the same name in the comment example as the properties in Schema.org, you can see there the namespaces even though it is not used. In case no more is added to that file, I think that using an already defined property is a better approach.

**Comment by InigoGutierrez** [comment]
Formatting details: note that in bikeshed the final octothorpes are to be used only if the title has an ID, otherwise they appear in the final text. I added IDs to the titles so this doesn't happen and they can be referenced later if needed. Also, when building locally the json-ld route example is imported but appears as plain text without formatting. I was not able to solve this issue.

**Comment by InigoGutierrez** [comment]
I noticed that we are missing a specification for notifications to the inbox folder; I made one as a simplified version of the one proposed on https://github.com/Arquisoft/viadeSpec/issues/34#issuecomment-605993634 in jsonld format. I am no expert with these, so take this proposal with care.

```
{
  "@context": "https://www.w3.org/ns/activitystreams",
  "summary": "Sally offered 50% off to Lewis",
  "type": "Offer",
  "actor": {
    "type": "Person",
    "name": "Alice"
  },
  "object": {
    "type": "http://www.types.example/ProductOffer",
    "name": "50% Off!"
  },
  "target": {
    "type": "Person",
    "name": "Bob"
  }
}
```

We could add this to the proposal so we have a reference to make a base format for interoperability.

**Comment by labra** [comment]
Given that several people have said me that they agree with this pull-request, I proceed to merge it.

**Pull request merged**
